export const MENU_NAVIGATION_MAP: Record<string, { view: string; dashboardTitle?: string; dashboardActiveItem?: string }> = {
  "caixa de mensagens": { view: "dashboard", dashboardTitle: "Caixa de Mensagens", dashboardActiveItem: "Caixa de Mensagens" },
  "assinatura digital": { view: "assinatura_digital" },
  "economato": { view: "economato", dashboardTitle: "Gestão de Economato" },
  "gestão de economato": { view: "economato", dashboardTitle: "Gestão de Economato" },
  "gestão patrimonial": { view: "gestao_patrimonial" },
  "documentos normativos": { view: "documentos_normativos" },
  "relatórios": { view: "relatorios" },
  "gestão de colaboradores": { view: "colaboradores", dashboardTitle: "Gestão de Colaboradores", dashboardActiveItem: "Gestão de Pessoal" },
  "gestão de pessoal": { view: "colaboradores", dashboardTitle: "Gestão de Colaboradores", dashboardActiveItem: "Gestão de Pessoal" },
  "monografia": { view: "monografia" },
  "gerar monografia": { view: "monografia" },
  "gestão de produtos e preços": { view: "produtos_precos" },
  "gestão de fornecedores": { view: "supplier_management" },
  "fornecedores": { view: "supplier_management" },
  "registo de fornecedores": { view: "supplier_form" },
  "registo de fornecedor": { view: "supplier_form" },
  "plano de aquisição": { view: "plano_aquisicao" },
  "plano de contratação": { view: "plano_contratacao" },
};
