export const MENU_NAVIGATION_MAP: Record<string, { view: string; dashboardTitle?: string; dashboardActiveItem?: string }> = {
  "caixa de mensagens": { view: "dashboard", dashboardTitle: "Caixa de Mensagens", dashboardActiveItem: "Caixa de Mensagens" },
  "assinatura digital": { view: "assinatura_digital", dashboardTitle: "Assinatura Digital" },
  "economato": { view: "economato", dashboardTitle: "Gestão de Economato" },
  "gestão de economato": { view: "economato", dashboardTitle: "Gestão de Economato" },
  "gestao de economato": { view: "economato", dashboardTitle: "Gestão de Economato" },
  "gestão patrimonial": { view: "gestao_patrimonial", dashboardTitle: "Gestão Patrimonial" },
  "gestao patrimonial": { view: "gestao_patrimonial", dashboardTitle: "Gestão Patrimonial" },
  "documentos normativos": { view: "documentos_normativos", dashboardTitle: "Documentos Normativos" },
  "relatórios": { view: "relatorios", dashboardTitle: "Relatórios" },
  "relatorios": { view: "relatorios", dashboardTitle: "Relatórios" },
  "gestão de colaboradores": { view: "colaboradores", dashboardTitle: "Gestão de Colaboradores", dashboardActiveItem: "Gestão de Pessoal" },
  "gestao de colaboradores": { view: "colaboradores", dashboardTitle: "Gestão de Colaboradores", dashboardActiveItem: "Gestão de Pessoal" },
  "gestão de pessoal": { view: "colaboradores", dashboardTitle: "Gestão de Colaboradores", dashboardActiveItem: "Gestão de Pessoal" },
  "gestao de pessoal": { view: "colaboradores", dashboardTitle: "Gestão de Colaboradores", dashboardActiveItem: "Gestão de Pessoal" },
  "monografia": { view: "monografia", dashboardTitle: "Monografia" },
  "gerar monografia": { view: "monografia", dashboardTitle: "Monografia" },
  "gestão de produtos e preços": { view: "produtos_precos", dashboardTitle: "Gestão de Produtos e Preços" },
  "gestao de produtos e precos": { view: "produtos_precos", dashboardTitle: "Gestão de Produtos e Preços" },
  "produtos e preços": { view: "produtos_precos", dashboardTitle: "Gestão de Produtos e Preços" },
  "produtos e precos": { view: "produtos_precos", dashboardTitle: "Gestão de Produtos e Preços" },
  "gestão de fornecedores": { view: "supplier_management", dashboardTitle: "Gestão de Fornecedores" },
  "gestao de fornecedores": { view: "supplier_management", dashboardTitle: "Gestão de Fornecedores" },
  "fornecedores": { view: "supplier_management", dashboardTitle: "Gestão de Fornecedores" },
  "registo de fornecedores": { view: "supplier_form", dashboardTitle: "Registo de Fornecedor" },
  "registo de fornecedor": { view: "supplier_form", dashboardTitle: "Registo de Fornecedor" },
  "novo registo de fornecedor": { view: "supplier_form", dashboardTitle: "Registo de Fornecedor" },
  "novo registo de fornecedores": { view: "supplier_form", dashboardTitle: "Registo de Fornecedor" },
  "plano de aquisição": { view: "plano_aquisicao", dashboardTitle: "Plano de Aquisição" },
  "plano de aquisicao": { view: "plano_aquisicao", dashboardTitle: "Plano de Aquisição" },
  "plano de contratação": { view: "plano_contratacao", dashboardTitle: "Plano de Contratação" },
  "plano de contratacao": { view: "plano_contratacao", dashboardTitle: "Plano de Contratação" },
  "entrada de expediente": { view: "gestao_documentos", dashboardTitle: "Entrada de Expediente" },
  "saída de expediente": { view: "gestao_documentos", dashboardTitle: "Saída de Expediente" },
  "saida de expediente": { view: "gestao_documentos", dashboardTitle: "Saída de Expediente" },
  "gestão de documentos": { view: "gestao_documentos", dashboardTitle: "Gestão de Documentos" },
  "gestao de documentos": { view: "gestao_documentos", dashboardTitle: "Gestão de Documentos" },
  "reposição de teste": { view: "reposicao_teste", dashboardTitle: "Reposição de Teste" },
  "reposicao de teste": { view: "reposicao_teste", dashboardTitle: "Reposição de Teste" },
  "visita à biblioteca": { view: "library_visit", dashboardTitle: "Visita à Biblioteca" },
  "visita a biblioteca": { view: "library_visit", dashboardTitle: "Visita à Biblioteca" },
  "gestão da biblioteca": { view: "library_management", dashboardTitle: "Gestão da Biblioteca" },
  "gestao da biblioteca": { view: "library_management", dashboardTitle: "Gestão da Biblioteca" },
  "manual de instruções": { view: "manual_instrucoes", dashboardTitle: "Manual de Instruções" },
  "manual de instrucoes": { view: "manual_instrucoes", dashboardTitle: "Manual de Instruções" },
  "projeto científico": { view: "projeto_cientifico", dashboardTitle: "Projeto Científico" },
  "projeto cientifico": { view: "projeto_cientifico", dashboardTitle: "Projeto Científico" },
};
