export const holidays2026 = [
  {
    id: "h-1",
    title: "Ano Novo",
    date: "2026-01-01",
    type: "Feriado Nacional",
    startTime: "",
    endTime: "",
    location: "",
    participants: "",
    agenda: "",
  },
  {
    id: "h-2",
    title: "Dia dos Heróis Moçambicanos",
    date: "2026-02-03",
    type: "Feriado Nacional",
    startTime: "",
    endTime: "",
    location: "",
    participants: "",
    agenda: "",
  },
  {
    id: "h-3",
    title: "Dia da Mulher Moçambicana",
    date: "2026-04-07",
    type: "Feriado Nacional",
    startTime: "",
    endTime: "",
    location: "",
    participants: "",
    agenda: "",
  },
  {
    id: "h-4",
    title: "Dia Int. dos Trabalhadores",
    date: "2026-05-01",
    type: "Feriado Nacional",
    startTime: "",
    endTime: "",
    location: "",
    participants: "",
    agenda: "",
  },
  {
    id: "h-5",
    title: "Dia Int. da Função Pública",
    date: "2026-06-23",
    type: "Feriado Nacional",
    startTime: "",
    endTime: "",
    location: "",
    participants: "",
    agenda: "",
  },
  {
    id: "h-6",
    title: "Dia da Independência Nacional",
    date: "2026-06-25",
    type: "Feriado Nacional",
    startTime: "",
    endTime: "",
    location: "",
    participants: "",
    agenda: "",
  },
  {
    id: "h-7",
    title: "Dia do Songo",
    date: "2026-07-27",
    type: "Feriado Institucional",
    startTime: "",
    endTime: "",
    location: "",
    participants: "",
    agenda: "",
  },
  {
    id: "h-8",
    title: "Dia da Vitória",
    date: "2026-09-07",
    type: "Feriado Nacional",
    startTime: "",
    endTime: "",
    location: "",
    participants: "",
    agenda: "",
  },
  {
    id: "h-9",
    title: "Dia das Forças Armadas de Defesa de Moçambique",
    date: "2026-09-25",
    type: "Feriado Nacional",
    startTime: "",
    endTime: "",
    location: "",
    participants: "",
    agenda: "",
  },
  {
    id: "h-10",
    title: "Dia da Paz e Reconciliação",
    date: "2026-10-04",
    type: "Feriado Nacional",
    startTime: "",
    endTime: "",
    location: "",
    participants: "",
    agenda: "",
  },
  {
    id: "h-11",
    title: "Dia dos Professores",
    date: "2026-10-12",
    type: "Data Comemorativa",
    startTime: "",
    endTime: "",
    location: "",
    participants: "",
    agenda: "",
  },
  {
    id: "h-12",
    title: "Dia da Família",
    date: "2026-12-25",
    type: "Feriado Nacional",
    startTime: "",
    endTime: "",
    location: "",
    participants: "",
    agenda: "",
  },
];
