export const PROVINCIAS_DISTRITOS: Record<string, string[]> = {
  "Maputo Cidade": [
    "KaMpfumo",
    "Nlhamankulu",
    "KaMaxakeni",
    "KaMavota",
    "KaMubukwana",
    "KaTembe",
    "KaNyaka",
  ],
  Maputo: [
    "Boane",
    "Magude",
    "Manhiça",
    "Marracuene",
    "Matola",
    "Matutuíne",
    "Moamba",
    "Namaacha",
  ],
  Gaza: [
    "Bilene",
    "Chibuto",
    "Chicualacuala",
    "Chigubo",
    "Chókwè",
    "Chonguene",
    "Guijá",
    "Limpopo",
    "Mabalane",
    "Macia",
    "Mandlakazi",
    "Mapai",
    "Massangena",
    "Massingir",
    "Xai-Xai",
  ],
  Inhambane: [
    "Funhalouro",
    "Govuro",
    "Homoíne",
    "Inhambane",
    "Inharrime",
    "Inhassoro",
    "Jangamo",
    "Mabote",
    "Massinga",
    "Maxixe",
    "Morrumbene",
    "Panda",
    "Vilankulo",
    "Zavala",
  ],
  Sofala: [
    "Beira",
    "Búzi",
    "Caia",
    "Chemba",
    "Cheringoma",
    "Chibabava",
    "Dondo",
    "Gorongosa",
    "Machanga",
    "Maringué",
    "Muanza",
    "Nhamatanda",
  ],
  Manica: [
    "Bárue",
    "Chimoio",
    "Gondola",
    "Guro",
    "Macate",
    "Machaze",
    "Macossa",
    "Manica",
    "Mossurize",
    "Sussundenga",
    "Tambara",
    "Vanduzi",
  ],
  Tete: [
    "Angónia",
    "Cahora-Bassa",
    "Changara",
    "Chifunde",
    "Chiúta",
    "Dôa",
    "Macanga",
    "Magoé",
    "Marávia",
    "Moatize",
    "Mutarara",
    "Cidade de Tete",
    "Tsangano",
    "Zumbo",
  ],
  Zambézia: [
    "Alto Molócuè",
    "Chinde",
    "Derre",
    "Gilé",
    "Gurué",
    "Ile",
    "Inhassunge",
    "Luabo",
    "Lugela",
    "Maganja da Costa",
    "Milange",
    "Mocuba",
    "Mocubela",
    "Molumbo",
    "Mopeia",
    "Morrumbala",
    "Mulevala",
    "Namacurra",
    "Namarroi",
    "Nicoadala",
    "Pebane",
    "Quelimane",
  ],
  Nampula: [
    "Angoche",
    "Eráti",
    "Ilha de Moçambique",
    "Lalaua",
    "Larde",
    "Liúpo",
    "Macomia",
    "Mecubúri",
    "Memba",
    "Mogincual",
    "Mogovolas",
    "Moma",
    "Monapo",
    "Mossuril",
    "Muecate",
    "Murrupula",
    "Nacala-a-Velha",
    "Nacala Porto",
    "Nampula",
    "Rapale",
    "Ribáuè",
  ],
  "Cabo Delgado": [
    "Ancuabe",
    "Balama",
    "Chiúre",
    "Ibo",
    "Macomia",
    "Mecúfi",
    "Meluco",
    "Metuge",
    "Mocímboa da Praia",
    "Montepuez",
    "Mueda",
    "Muidumbe",
    "Namuno",
    "Nangade",
    "Palma",
    "Pemba",
    "Quissanga",
  ],
  Niassa: [
    "Chimbonila",
    "Cuamba",
    "Lago",
    "Lichinga",
    "Majune",
    "Mandimba",
    "Marrupa",
    "Maúa",
    "Mavago",
    "Mecanhelas",
    "Mecula",
    "Metarica",
    "Muembe",
    "N'gauma",
    "Nipepe",
    "Sanga",
  ],
};

export const UNIDADES_ORGANICAS = [
  "Gabinete do Diretor-Geral",
  "DICOSAFA",
  "DICOSSER",
  "Divisão de Engenharia",
  "Departamento de Recursos Humanos",
  "Repartição de Pessoal",
  "Repartição de Formação",
  "Repartição de Apoio Social",
  "Departamento de Finanças",
  "Repartição de Plano e Orçamento",
  "Repartição de Tesouraria",
  "Departamento de Património",
  "Repartição de Infraestrutura",
  "Repartição de Transporte",
  "Repartição de Manutenção",
  "Secretaria Geral",
  "Departamento TIC",
  "Departamento Lar de Estudantes",
  "Departamento de Produção Alimentar",
  "Departamento de Registo Académico",
  "Departamento de Assuntos Estudantis",
  "Departamento de Biblioteca",
  "Repartição de Documentos",
  "Repartição de Arquivo",
];
